version: '3.8'

services:
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: graziella-frontend
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - frontend-network

networks:
  frontend-network:
    driver: bridge
